// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxz8fCnb5-0N0h3kuktsHC9eiIFKKqQz4',
    appId: '1:105836744617:web:eb9709da2120fcd6d9beb8',
    messagingSenderId: '105836744617',
    projectId: 'completequiz-8c9aa',
    authDomain: 'completequiz-8c9aa.firebaseapp.com',
    storageBucket: 'completequiz-8c9aa.firebasestorage.app',
    measurementId: 'G-R1SMD6FE75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSccvB-GChkDOmRuv7wiHOhYuFPxxlXcA',
    appId: '1:105836744617:android:d28d4c80163ec42bd9beb8',
    messagingSenderId: '105836744617',
    projectId: 'completequiz-8c9aa',
    storageBucket: 'completequiz-8c9aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTip8AC8ugMnPthfo_OGMp1DJWF_wpUB4',
    appId: '1:105836744617:ios:f8455fa60041ca41d9beb8',
    messagingSenderId: '105836744617',
    projectId: 'completequiz-8c9aa',
    storageBucket: 'completequiz-8c9aa.firebasestorage.app',
    iosBundleId: 'com.example.completeQuiz',
  );
}
